vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: stylebox.local
        memory: '4096'
        cpus: '4'
        chosen_provider: virtualbox
        network:
            public_network: 10.0.1.181
            private_network: 192.168.56.101
            forwarded_port:
                vflnp_17tbw341sb9o:
                    host: '8080'
                    guest: '80'
                vflnp_iu2ri3ck7oxu:
                    host: '2223'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                    rtcuseutc: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_g31fi4mm270m:
                source: /Users/vagranthost/Vagrant/stylebox/var/www
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        insert_key: false
        private_key_path: '/Users/vagranthost/Vagrant/.ssh/id_rsa'
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups:
        - www-data
    users:
        - 'www-data:www-data'
        - 'vagrant:www-data'
locale:
    install: '1'
    settings:
        default_locale: ''
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_9af5jpme39jt:
            servername: stylebox.atlas
            serveraliases:
                - stylebox.atlas
            docroot: /var/www/html/styleguide
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_4f41kxrs6swa:
                    path: /var/www/html/styleguide
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_a0c36ci319sp:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
        av_vsn0cftm02h7:
            servername: stylebox.barfinder
            serveraliases:
                - stylebox.barfinder
            docroot: /var/www/html/styleguide
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
        av_jenab8kaiwte:
            servername: stylebox
            docroot: /var/www/html
            port: '80'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - imagick
            - gd
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_hoqkvk50vpox:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-data
                group: www-data
    composer: '1'
    composer_home: ''
wpcli:
    install: '0'
    version: v0.19.0
drush:
    install: '1'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
python:
    install: '0'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    npm_packages: {  }
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: sushi
        override_options: {  }
    adminer: 1
    users:
        mysqlnu_vuq382m39kb8:
            name: styler
            password: sushi
    databases:
        mysqlnd_4fvto24wvrcp:
            name: stylebox_atlas
            sql: ''
        mysqlnd_oo8m52vfz9am:
            name: styleguide_barfinder
            sql: ''
        mysqlnd_kj1zss7idf4n:
            name: styleguide
            sql: ''
    grants:
        mysqlng_8j307sp22l45:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
        mysqlng_gvlh2yap7pmv:
            user: styler
            table: '*.*'
            privileges:
                - ALL